hash-format = "sha256"

[[files]]
file = "README.md"
hash = "b8d6507f93c414df3eefcae7b72e77b0034290d059242f8a01c80cfb14c5b882"

[[files]]
file = "icon.png"
hash = "8d4d6cb29533676487f8130ec8df6615ee90bdb6b5121037562a93c8d487e284"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "4fb7aa571d469a6ee7e359ab9d018c90236575c2f55b1fa1cfbfdd0cccf41ae8"
metafile = true

[[files]]
file = "mods/actually-harvest.pw.toml"
hash = "cb06af41fe6ce14cef5b0f92f3f7c8e61eb53f0529cee0f67cd88c50e9424f83"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "da732b5c94d44c8d880ac7b00c2ee49c6674a145b2e620e646ec5eb3a564bd02"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "5a53be204efcb61ed865b934d60f0ed29fa74d02ebecb1276f668d6baa57e40b"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "0af6e4bea463dbf2f08bfce33c57ae274f06f64284007c9717ea087ee766ecc1"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "a8a81275cdf9239baa3a83978b649fe80dd90b15d7199d47fc33fd0afbe22e6f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/cluttered.pw.toml"
hash = "4ae3ce4646699d18f72e70465d66dff8f5926576874f80d0fca6a70033c27ca9"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "d8480ee1f6ae58fa389e502108bcde4936ca326d6dc2f1608b9af9ac141cb35a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "4d5ba0ec7ea7abf0ef76f3f08853bd7c886eec95b1795cbeacaba8bc608e2913"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "b2c7739b56ef71f50a86658cfa67375796beafd391c4dbe26a5de8cd92b9b685"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "9582c04926dd9cea7f68f6f1b4e068bd2ec3f6fcb2734497d885364c6b74b1e1"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "88325807c01b522a76d686f39c442da99b73a90ae3ec9b5434fea5f79baa4d49"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "ac4cbd7785b8c70de4037162d6626910633e6b997c957e90de961316716e8402"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "f3a249ba62f2c0036e54b56e0362e3090d16aa850b8a4fbe7f35a6cf7f483bfa"
metafile = true

[[files]]
file = "mods/do-api.pw.toml"
hash = "35e3ed00b7e0b2a3082ed35c677589ca762cd73e18858ad6ba7a4b6f7cdef441"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "65b63aece9a33ef9354ac44f316aeea188e98a9439f81f5d02b32415955090bc"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "abf637dc12d9a986fd28d03293030cef891c81ad2b04e533dfea5bb553d52beb"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "3b5b7d833a2dd0a0064371036ab1da338cbbf82fb42d84dc8078dc9f48a3b63c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7b32032b0892b53e1e5daf5410b78b4d98b7bdcbe2184f1d643098de36674865"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c7dfdcddf32a63084e0b54679e33378769bc4f48bd97f006008405da5e6df2ba"
metafile = true

[[files]]
file = "mods/explosive-enhancement-forge.pw.toml"
hash = "c995fb23f73672967c9f9ee906fd36e12491180e61c978bfeae3eba4d87c8517"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/from-the-cave.pw.toml"
hash = "a6c1a3e2ba9734205d6ca58e94d39f7f7e4fb630c352a1ebed29b5c23a366bc0"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "9c94815c028b18cd04c63b604209be515d209dff8f4bc9960867da0b13a0dfe8"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "67b0b2bd471fc2393c7c8e95cae5ae6031e621d11f5e253c07a4427857f1a2bd"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "f8312021fd88a4952e1d50a2f156fab65314f87658d7153efc56be76a422d5cd"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/lets-do-addon-apple-wood.pw.toml"
hash = "19b33225ad7a4fc2dc1fdb8d7036786e485920811697631dc9ce636ded913584"
metafile = true

[[files]]
file = "mods/lets-do-addon-compat.pw.toml"
hash = "62b4b429775b5226241b728e76ca2875f6eb01c0dfdfb2eee9447191452bd0c1"
metafile = true

[[files]]
file = "mods/lets-do-addon-corn-expansion.pw.toml"
hash = "53348ba42aabb5d27e9218c9fc3cafc5f7826137f7f1851d200cd242f80ac44d"
metafile = true

[[files]]
file = "mods/lets-do-addon-structures.pw.toml"
hash = "fd67dbff187e526321a7f7da6859cbd67d11da95111382b7d53673297c188411"
metafile = true

[[files]]
file = "mods/lets-do-bakery-farmcharm-compat.pw.toml"
hash = "ee9414dab42439269380159db091cde2e74a82222dafff660f34597f877b894a"
metafile = true

[[files]]
file = "mods/lets-do-beachparty.pw.toml"
hash = "d78e971517d18ba6628d707e5a4a379e68499893ce17e92e490e945b3c60e115"
metafile = true

[[files]]
file = "mods/lets-do-bloomingnature.pw.toml"
hash = "4ee14fa7c3443a84ef418f4cfcb92844ec37761adf9d59a7e71eda377bf90e5a"
metafile = true

[[files]]
file = "mods/lets-do-brewery-farmcharm-compat.pw.toml"
hash = "dc533948303a37b23a88472ecf90f16882a9a27bca8dbbc835e26dfb3f109e78"
metafile = true

[[files]]
file = "mods/lets-do-camping.pw.toml"
hash = "8427e0c8750dac7a5bd0f58da78986e6e85de8a12e506700d401b07b9328efe4"
metafile = true

[[files]]
file = "mods/lets-do-candlelight-farmcharm-compat.pw.toml"
hash = "958ea5b62a016532c09d1bc49c5cc1e7d7ca74b83b19ddf8aaceb0d58f8811ac"
metafile = true

[[files]]
file = "mods/lets-do-emi-compat.pw.toml"
hash = "0513ca3f8c33845f8d9301fe942d6149e4b268da5971943db4c9c212b96b096d"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "b684e31e68e4f0fe7a418afbdc2318a044d208ffdd9b19ea9d4f0ab918536efd"
metafile = true

[[files]]
file = "mods/lets-do-furniture.pw.toml"
hash = "a8aace9988ad0726659d4eea06edf4fb350b7b1db5ffa9ab38770b06e570b7b0"
metafile = true

[[files]]
file = "mods/lets-do-herbalbrews.pw.toml"
hash = "b720172434e663a1e7d87e0b3b14c0fcbd0032bb14b4ed1885f5c4b32614994f"
metafile = true

[[files]]
file = "mods/lets-do-lilis-lucky-lures.pw.toml"
hash = "0d6eafc42049c16833dea754706484d2d9c3387ef3430dae4ce2ebeb9d39adcb"
metafile = true

[[files]]
file = "mods/lets-do-meadow.pw.toml"
hash = "901dc04b960669a18e321a730891c0334efc0a6b0470593b671ce3874eaf8d1f"
metafile = true

[[files]]
file = "mods/lets-do-nethervinery.pw.toml"
hash = "272687249859fff5269bfab12605d2d3a42e1e51cd1fdaadf5d05ee6571519b2"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "94255c24694569e26337079e3ff81165b4e914ab427d4dab0e1d78b65325ba9f"
metafile = true

[[files]]
file = "mods/lets-do-wildernature.pw.toml"
hash = "9466b6e09a2342d0416dadab27582cc439dce7ed6efe28b8ea5a79564a27cd3e"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "457f1d7c34cb8cb605b002fee89d3f0a766eb461ef82236c48cb1196b1e81a97"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "66bcfe786e6bbdee6f7ea0805ec3d2561b41285a5c77f1e465e80f4c2fd9200c"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "8dd17f19e28b517c1ce56a2024ece8a37ca9bc866079d23969cc3811577861a4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "071ce6bcd5614ceb07718b646f1012faf9c449eb8e56c0b740929a9efada593c"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "acaf74883794f150634fbaf000e15098162610d2e1ef2d4029a64c7b0fe71e6e"
metafile = true

[[files]]
file = "mods/omnicut-better-wood-stone-cutter.pw.toml"
hash = "fc81805cbce149290a3f5adbb8bca08806d864e6fb6efba7c6d9e02a5890fa7f"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "3be4938aaa277d8f544fe2b2ca1b9903ddcb43a1426c96ee3aea47c4eac6e07b"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "281fc0b9bde0b16347f931c60b53ef60a92c5b80bd21296a5cb24fccf3dbbafd"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "c3f63fc5f823fe29561fbbc9deb3957d991fb9331c62a5ae27ec3cad6b1265a7"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "ed8bf57c00a377d998b1df2c2390573bdf34214e63e01fed7d813914cdac7993"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "767f1d29cf465dc38d5ef9a93b2a9d4c54daad8c82535d525070efd97f504ad9"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "35c4484a3bd6b9055f3f944ed8bdc27fb8c62a385277b9e7f89fd19bccfa4191"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e4b99d45d1cfb55b0ecd2aa78c56958b57460e63b637448017df60b2412e77d9"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "3042b51312180a3d24c0890f03e4c43b31b1a19b65de87f0e440d335ee81cafd"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
hash = "a291a8d50f30843e49d92db1cde7734327e809b52d24183eecff8c165eed82a6"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "82bb7cd6c8b68bb1831bb7c374bd316b6403cd01195d582f19c31076c908953a"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "75a60e6b443b351b7a4a78ffce7c71e44b3e20ca10c374aea1de516c785d6e2d"
metafile = true

[[files]]
file = "mods/sodium-options-mod-compat.pw.toml"
hash = "59594325144bb9f970d43990071858e56044560c9b77cce74b79e4fcb4b41f70"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "416bb6449da951ec1a04156348c502b9e47a947212becc173d277faaddaaaccd"
metafile = true

[[files]]
file = "mods/spelunkery.pw.toml"
hash = "cda6e32875942f8893b3f08645da60d280b2c45e16a9eedbc334a89329c0fa3d"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "f5271ae838cfc821af13a9c598e8bb0982e275a9e26ed431a257b901f4ed9df4"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3848bc11aa2acabef74eb85ca74b8ca8e23733b7fcbc77293165c5c7161e3288"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "99b4a4fe0eafd761a298c00269ee2aa12c4eb3fa67a7a09a5ca6758882fd67f5"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "f26fb3886f4c53b3284264cacfebb4bfe68a189205363e8e406896c847c1e0ea"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "72c0e1d4d8eb05e6c82c8959885ee5f08b8c7ede63b438e22a7422246679cc46"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "f156304cd261a234aee02630dc33e8ad6b3a10898d5b0a7069d1a88f9b607813"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "c557d1b26559ef987c229187d2f2705616e78179ce04fa1c96cc3d76a1cdf1b5"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
hash = "bbec88a5550466b7303b26f32ac82e471474697b590980822b06c6967d418d15"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "c35112cced2eec8e5782c5c4327ae31bce16cc1356c75e52000053e890e0f0c1"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "302d69d833264022aa7ff781dbcde7f60f3c9e3021881b29f6f59223c36579c8"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "8c8b596c0e8f7366e30ee6edbd591fba9ef16741c25a505e64de9a299cd72e80"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "41aa01e9d0507d3131eb5fd2f6d8f2b7c54237e30a94e2a3bf6f52915cb8a688"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "05f825a655bc94af6ab592d13c396b60c818cfc65ff2528e206e7a40a180e210"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "60511ad5628ed8e45a552de171c3330bdcdbd5f86f7047e26b505b7a8c824a47"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "18dfe8ada0af83eb86d4b8ff8e202479b7c2ab1ee1f894d9bb07cda1744e8981"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.pw.toml"
hash = "66fd4a47f4eb3fc7b0e487b0fafc998f009e889188bcc5a609d04c2ab97e369f"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/fancyfast-bushy-leaves.pw.toml"
hash = "2a61421eeb20758224c372b28640103661c434f2ecbf4c15153f0a655a548591"
metafile = true

[[files]]
file = "resourcepacks/fine-armoury.pw.toml"
hash = "84eb4bf56150f20451bd3687959a41ff06b52e3b7335e7f2c50d8a7c418876f5"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-creepers.pw.toml"
hash = "bc82402c88e6809625c18a01b9eb85b0885a1c44fd3293979eb4c12871691408"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-details.pw.toml"
hash = "595e82727529453141a910c99f27302a908b5488ca782a9a1d99809276630786"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-emissive.pw.toml"
hash = "dcd0431bf5f45761e679ed20cae3e913e02e6eb06e572d3d37e81d002ac47f5e"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-objects.pw.toml"
hash = "a91bf9ed0c2ff42ceafdea4e94eb4378bc54d807b60fd5486bfb6ffdbfc6ed2e"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-spiders.pw.toml"
hash = "8c80dec7ad533aa7d71f6830c1a1703771025d6814803e72b706fe8a7d0e229b"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "42b8a59616b3ed15a02e55466dff7ab400d481a8730949ce0168a927b71b91fb"
metafile = true

[[files]]
file = "resourcepacks/fusion-block-transitions.pw.toml"
hash = "e5f49f7a3b49f7a03f667c5c5ca43826e7abbfcc0a9fe2499af89b461fac0819"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-blocks.pw.toml"
hash = "0e27eea95511f0914b8db1e75cfde84ca748251bc5d24c42dd9af38abd77afdc"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-glass.pw.toml"
hash = "cc4c03200baa367d40720320336b692e6c4fe71edbea890e27210bb2cc42408c"
metafile = true

[[files]]
file = "resourcepacks/simple-grass-flowers.pw.toml"
hash = "bc4dcbd6b77adb2180049d63ed4a8981553f06dbf3e32080022ffd87dd1fb09b"
metafile = true

[[files]]
file = "resourcepacks/simple-lower-grass-sides.pw.toml"
hash = "95df280d41e71aa4a6db43b9f56196a716f238660b0135c05155980e36778304"
metafile = true

[[files]]
file = "resourcepacks/sparkles.pw.toml"
hash = "4d1f80d4aea6f81427b67313796afa14e4319d6284ea512169243a74f7c74ba7"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "a2281fdf9db2f273f97a5c17d0179e8e104372ba0539ff50145e9fba28c3dc69"
metafile = true
