name = "Spooky Charm"
author = "kodiitulip"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "966d8cb5017a6bdbf6fd34af5f3d1fc8025c04abde3330c6aa3141ab7172320a"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
